local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
amazon:
  service: S3
  access_key_id: ""
  secret_access_key: ""
  bucket: "zonankalaloo"
  region: "us-east-2"
#   local:
#   service: Disk
#   root: <%= Rails.root.join("storage") %>

# test:
#   service: Disk
#   root: <%= Rails.root.join("tmp/storage") %>
