local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
 
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
 
# amazon:
#   service: S3
#   access_key_id: ""
#   secret_access_key: ""
#   bucket: ""
#   region: "" # e.g. 'us-east-1'

# amazon:
#   service: S3
#   access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
#   secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
#   region: ap-south-1
#   bucket: my-bucket